INSERT INTO Album (albumID, `name`, releaseYear, thumbnail, artistID)
VALUES (1, 'Coat of Arms', 2010, 'sabaton_coatofarms.jpg', 2)
    , (2, 'Carolus Rex', 2012, 'sabaton_carolusrex.jpg', 2)
    , (3, 'The Last Stand', 2016, 'sabaton_thelaststand.jpg', 2)
    , (4, 'Bismarck', 2019, 'sabaton_bismarck.jpg', 2)
    , (5, 'The Great War', 2019, 'sabaton_thegreatwar.jpg', 2)
    , (6, 'These Two Windows', 2020, 'alecbenjamin_thesetwowindows.jpg', 3)
    , (7, 'Narrated For You', 2018, 'alecbenjamin_narratedforyou.jpg', 3)
    , (8, 'Paris in the Rain', 2018, 'lauv_parisintherain.jpg', 4)
    , (9, 'A Place We Knew', 2019, 'deanlewis_aplaceweknew.jpg', 5)
    , (10, 'Be Alright', 2018, 'deanlewis_bealright.jpg', 5);