INSERT INTO Album (`name`, releaseYear, thumbnail, artistID)
VALUES ('Coat of Arms', 2010, 'sabaton_coatofarms.jpg', 2)
    , ('Carolus Rex', 2012, 'sabaton_carolusrex.jpg', 2)
    , ('The Last Stand', 2016, 'sabaton_thelaststand.jpg', 2)
    , ('Bismarck', 2019, 'sabaton_bismarck.jpg', 2)
    , ('The Great War', 2019, 'sabaton_thegreatwar.jpg', 2)
    , ('These Two Windows', 2020, 'alecbenjamin_thesetwowindows.jpg', 3)
    , ('Narrated For You', 2018, 'alecbenjamin_narratedforyou.jpg', 3)
    , ('Paris in the Rain', 2018, 'lauv_parisintherain.jpg', 4)
    , ('A Place We Knew', 2019, 'deanlewis_aplaceweknew.jpg', 5)
    , ('Be Alright', 2018, 'deanlewis_bealright.jpg', 5);